exclude: tests/cases/(refactor|source).*

repos:
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort

  - repo: https://github.com/hakancelikdev/unimport
    rev: 0.12.1
    hooks:
      - id: unimport
        args: [--config=pyproject.toml]

  - repo: https://github.com/PyCQA/docformatter
    rev: v1.5.0
    hooks:
      - id: docformatter
        args: [--config=pyproject.toml]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.982
    hooks:
      - id: mypy
        additional_dependencies: [types-toml==0.1.3]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.1
    hooks:
      - id: prettier
        args: [--prose-wrap=always, --print-width=88]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: end-of-file-fixer
        files: "\\.(py|.txt|.yaml|.json|.in|.md|.toml|.cfg|.html|.yml)$"

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.1.0
    hooks:
      - id: pyupgrade
        args: [--py36-plus]

  - repo: https://github.com/hakancelikdev/pyall
    rev: d2897f7df4418e4e0c6b7a9dd7edb3761a46333d
    hooks:
      - id: pyall
        args:
          - --refactor
          - --exclude=tests|setup.py|__init__.py|
